name: rewriter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/Intro1.png
    - assets/images/Intro2.png
    - assets/images/Intro3.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500